import { createFileRoute } from "@tanstack/react-router";
import { Film, Instagram, Languages, Moon, Send, UploadCloud } from "lucide-react";
import { CaseMindShell } from "@/components/CaseMindShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/settings")({ component: SettingsPage });

function SettingsPage() {
  return <CaseMindShell><section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><Moon className="mb-5 h-10 w-10 text-accent" /><h1 className="text-5xl font-black text-foreground">Sozlamalar va social studio</h1><div className="mt-8 grid gap-4 sm:grid-cols-3">{["O‘zbek", "Русский", "English", "Deutsch", "اردو", "Türkçe"].map((x) => <button key={x} className="rounded-2xl border bg-card p-6 text-left shadow-premium transition hover:-translate-y-1"><Languages className="mb-4 h-6 w-6 text-accent" />{x}</button>)}</div><div className="mt-10 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="premium-card rounded-2xl border p-6 shadow-premium"><p className="text-sm font-semibold uppercase text-accent">Connector ready</p><h2 className="mt-2 text-3xl font-black text-foreground">Instagram va Telegram ulash</h2><p className="mt-3 leading-7 text-muted-foreground">Bu yer social kanallarni ulash va media reja tayyorlash markazi. Telegram connector keyingi bosqichda real bot/kanalga post yuborish uchun ulanadi; Instagram uchun kanal havolasi va kontent workflow tayyor.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Button variant="premium"><Instagram className="h-4 w-4" /> Instagram sozlash</Button><Button variant="legal"><Send className="h-4 w-4" /> Telegram sozlash</Button></div></div><form className="rounded-2xl border bg-card p-6 shadow-premium"><div className="flex items-center gap-3"><Film className="h-8 w-8 text-accent" /><div><p className="text-sm font-semibold uppercase text-accent">Media upload</p><h2 className="text-3xl font-black text-foreground">Video yoki post tayyorlash</h2></div></div><div className="mt-6 grid gap-4"><Input placeholder="Post sarlavhasi" className="bg-background" /><Textarea placeholder="Caption / matn / huquqiy izoh" className="min-h-28 bg-background" /><Input type="file" accept="video/*,image/*" className="h-auto bg-background py-3" /><Button variant="premium" type="button"><UploadCloud className="h-4 w-4" /> Kontentni saqlash</Button></div></form></div></section></CaseMindShell>;
}
