/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlenumQarorlariRouteImport } from './routes/plenum-qarorlari'
import { Route as MamlakatlarRouteImport } from './routes/mamlakatlar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JinoyatKodeksiRouteImport } from './routes/jinoyat-kodeksi'
import { Route as HuquqBolimlariRouteImport } from './routes/huquq-bolimlari'
import { Route as CaseDatabaseRouteImport } from './routes/case-database'
import { Route as AiTahlilRouteImport } from './routes/ai-tahlil'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MamlakatlarCountryIdRouteImport } from './routes/mamlakatlar.$countryId'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const PlenumQarorlariRoute = PlenumQarorlariRouteImport.update({
  id: '/plenum-qarorlari',
  path: '/plenum-qarorlari',
  getParentRoute: () => rootRouteImport,
} as any)
const MamlakatlarRoute = MamlakatlarRouteImport.update({
  id: '/mamlakatlar',
  path: '/mamlakatlar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JinoyatKodeksiRoute = JinoyatKodeksiRouteImport.update({
  id: '/jinoyat-kodeksi',
  path: '/jinoyat-kodeksi',
  getParentRoute: () => rootRouteImport,
} as any)
const HuquqBolimlariRoute = HuquqBolimlariRouteImport.update({
  id: '/huquq-bolimlari',
  path: '/huquq-bolimlari',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseDatabaseRoute = CaseDatabaseRouteImport.update({
  id: '/case-database',
  path: '/case-database',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTahlilRoute = AiTahlilRouteImport.update({
  id: '/ai-tahlil',
  path: '/ai-tahlil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MamlakatlarCountryIdRoute = MamlakatlarCountryIdRouteImport.update({
  id: '/$countryId',
  path: '/$countryId',
  getParentRoute: () => MamlakatlarRoute,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tahlil': typeof AiTahlilRoute
  '/case-database': typeof CaseDatabaseRoute
  '/huquq-bolimlari': typeof HuquqBolimlariRoute
  '/jinoyat-kodeksi': typeof JinoyatKodeksiRoute
  '/login': typeof LoginRoute
  '/mamlakatlar': typeof MamlakatlarRouteWithChildren
  '/plenum-qarorlari': typeof PlenumQarorlariRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/mamlakatlar/$countryId': typeof MamlakatlarCountryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tahlil': typeof AiTahlilRoute
  '/case-database': typeof CaseDatabaseRoute
  '/huquq-bolimlari': typeof HuquqBolimlariRoute
  '/jinoyat-kodeksi': typeof JinoyatKodeksiRoute
  '/login': typeof LoginRoute
  '/mamlakatlar': typeof MamlakatlarRouteWithChildren
  '/plenum-qarorlari': typeof PlenumQarorlariRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/mamlakatlar/$countryId': typeof MamlakatlarCountryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-tahlil': typeof AiTahlilRoute
  '/case-database': typeof CaseDatabaseRoute
  '/huquq-bolimlari': typeof HuquqBolimlariRoute
  '/jinoyat-kodeksi': typeof JinoyatKodeksiRoute
  '/login': typeof LoginRoute
  '/mamlakatlar': typeof MamlakatlarRouteWithChildren
  '/plenum-qarorlari': typeof PlenumQarorlariRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/mamlakatlar/$countryId': typeof MamlakatlarCountryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tahlil'
    | '/case-database'
    | '/huquq-bolimlari'
    | '/jinoyat-kodeksi'
    | '/login'
    | '/mamlakatlar'
    | '/plenum-qarorlari'
    | '/api/ai-chat'
    | '/mamlakatlar/$countryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tahlil'
    | '/case-database'
    | '/huquq-bolimlari'
    | '/jinoyat-kodeksi'
    | '/login'
    | '/mamlakatlar'
    | '/plenum-qarorlari'
    | '/api/ai-chat'
    | '/mamlakatlar/$countryId'
  id:
    | '__root__'
    | '/'
    | '/ai-tahlil'
    | '/case-database'
    | '/huquq-bolimlari'
    | '/jinoyat-kodeksi'
    | '/login'
    | '/mamlakatlar'
    | '/plenum-qarorlari'
    | '/api/ai-chat'
    | '/mamlakatlar/$countryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTahlilRoute: typeof AiTahlilRoute
  CaseDatabaseRoute: typeof CaseDatabaseRoute
  HuquqBolimlariRoute: typeof HuquqBolimlariRoute
  JinoyatKodeksiRoute: typeof JinoyatKodeksiRoute
  LoginRoute: typeof LoginRoute
  MamlakatlarRoute: typeof MamlakatlarRouteWithChildren
  PlenumQarorlariRoute: typeof PlenumQarorlariRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plenum-qarorlari': {
      id: '/plenum-qarorlari'
      path: '/plenum-qarorlari'
      fullPath: '/plenum-qarorlari'
      preLoaderRoute: typeof PlenumQarorlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mamlakatlar': {
      id: '/mamlakatlar'
      path: '/mamlakatlar'
      fullPath: '/mamlakatlar'
      preLoaderRoute: typeof MamlakatlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinoyat-kodeksi': {
      id: '/jinoyat-kodeksi'
      path: '/jinoyat-kodeksi'
      fullPath: '/jinoyat-kodeksi'
      preLoaderRoute: typeof JinoyatKodeksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huquq-bolimlari': {
      id: '/huquq-bolimlari'
      path: '/huquq-bolimlari'
      fullPath: '/huquq-bolimlari'
      preLoaderRoute: typeof HuquqBolimlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-database': {
      id: '/case-database'
      path: '/case-database'
      fullPath: '/case-database'
      preLoaderRoute: typeof CaseDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tahlil': {
      id: '/ai-tahlil'
      path: '/ai-tahlil'
      fullPath: '/ai-tahlil'
      preLoaderRoute: typeof AiTahlilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mamlakatlar/$countryId': {
      id: '/mamlakatlar/$countryId'
      path: '/$countryId'
      fullPath: '/mamlakatlar/$countryId'
      preLoaderRoute: typeof MamlakatlarCountryIdRouteImport
      parentRoute: typeof MamlakatlarRoute
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MamlakatlarRouteChildren {
  MamlakatlarCountryIdRoute: typeof MamlakatlarCountryIdRoute
}

const MamlakatlarRouteChildren: MamlakatlarRouteChildren = {
  MamlakatlarCountryIdRoute: MamlakatlarCountryIdRoute,
}

const MamlakatlarRouteWithChildren = MamlakatlarRoute._addFileChildren(
  MamlakatlarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTahlilRoute: AiTahlilRoute,
  CaseDatabaseRoute: CaseDatabaseRoute,
  HuquqBolimlariRoute: HuquqBolimlariRoute,
  JinoyatKodeksiRoute: JinoyatKodeksiRoute,
  LoginRoute: LoginRoute,
  MamlakatlarRoute: MamlakatlarRouteWithChildren,
  PlenumQarorlariRoute: PlenumQarorlariRoute,
  ApiAiChatRoute: ApiAiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
