/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YuristlarRouteImport } from './routes/yuristlar'
import { Route as YuristBilanBoglanishRouteImport } from './routes/yurist-bilan-boglanish'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlenumQarorlariRouteImport } from './routes/plenum-qarorlari'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MamlakatlarRouteImport } from './routes/mamlakatlar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JinoyatKodeksiRouteImport } from './routes/jinoyat-kodeksi'
import { Route as HuquqBolimlariRouteImport } from './routes/huquq-bolimlari'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CaseDatabaseRouteImport } from './routes/case-database'
import { Route as AiTahlilRouteImport } from './routes/ai-tahlil'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MamlakatlarCountryIdRouteImport } from './routes/mamlakatlar.$countryId'
import { Route as HuquqBolimlariSlugRouteImport } from './routes/huquq-bolimlari.$slug'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const YuristlarRoute = YuristlarRouteImport.update({
  id: '/yuristlar',
  path: '/yuristlar',
  getParentRoute: () => rootRouteImport,
} as any)
const YuristBilanBoglanishRoute = YuristBilanBoglanishRouteImport.update({
  id: '/yurist-bilan-boglanish',
  path: '/yurist-bilan-boglanish',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlenumQarorlariRoute = PlenumQarorlariRouteImport.update({
  id: '/plenum-qarorlari',
  path: '/plenum-qarorlari',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MamlakatlarRoute = MamlakatlarRouteImport.update({
  id: '/mamlakatlar',
  path: '/mamlakatlar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JinoyatKodeksiRoute = JinoyatKodeksiRouteImport.update({
  id: '/jinoyat-kodeksi',
  path: '/jinoyat-kodeksi',
  getParentRoute: () => rootRouteImport,
} as any)
const HuquqBolimlariRoute = HuquqBolimlariRouteImport.update({
  id: '/huquq-bolimlari',
  path: '/huquq-bolimlari',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseDatabaseRoute = CaseDatabaseRouteImport.update({
  id: '/case-database',
  path: '/case-database',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTahlilRoute = AiTahlilRouteImport.update({
  id: '/ai-tahlil',
  path: '/ai-tahlil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MamlakatlarCountryIdRoute = MamlakatlarCountryIdRouteImport.update({
  id: '/$countryId',
  path: '/$countryId',
  getParentRoute: () => MamlakatlarRoute,
} as any)
const HuquqBolimlariSlugRoute = HuquqBolimlariSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HuquqBolimlariRoute,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/ai-tahlil': typeof AiTahlilRoute
  '/case-database': typeof CaseDatabaseRoute
  '/dashboard': typeof DashboardRoute
  '/huquq-bolimlari': typeof HuquqBolimlariRouteWithChildren
  '/jinoyat-kodeksi': typeof JinoyatKodeksiRoute
  '/login': typeof LoginRoute
  '/mamlakatlar': typeof MamlakatlarRouteWithChildren
  '/media': typeof MediaRoute
  '/notifications': typeof NotificationsRoute
  '/plenum-qarorlari': typeof PlenumQarorlariRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/yurist-bilan-boglanish': typeof YuristBilanBoglanishRoute
  '/yuristlar': typeof YuristlarRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/huquq-bolimlari/$slug': typeof HuquqBolimlariSlugRoute
  '/mamlakatlar/$countryId': typeof MamlakatlarCountryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/ai-tahlil': typeof AiTahlilRoute
  '/case-database': typeof CaseDatabaseRoute
  '/dashboard': typeof DashboardRoute
  '/huquq-bolimlari': typeof HuquqBolimlariRouteWithChildren
  '/jinoyat-kodeksi': typeof JinoyatKodeksiRoute
  '/login': typeof LoginRoute
  '/mamlakatlar': typeof MamlakatlarRouteWithChildren
  '/media': typeof MediaRoute
  '/notifications': typeof NotificationsRoute
  '/plenum-qarorlari': typeof PlenumQarorlariRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/yurist-bilan-boglanish': typeof YuristBilanBoglanishRoute
  '/yuristlar': typeof YuristlarRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/huquq-bolimlari/$slug': typeof HuquqBolimlariSlugRoute
  '/mamlakatlar/$countryId': typeof MamlakatlarCountryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/ai-tahlil': typeof AiTahlilRoute
  '/case-database': typeof CaseDatabaseRoute
  '/dashboard': typeof DashboardRoute
  '/huquq-bolimlari': typeof HuquqBolimlariRouteWithChildren
  '/jinoyat-kodeksi': typeof JinoyatKodeksiRoute
  '/login': typeof LoginRoute
  '/mamlakatlar': typeof MamlakatlarRouteWithChildren
  '/media': typeof MediaRoute
  '/notifications': typeof NotificationsRoute
  '/plenum-qarorlari': typeof PlenumQarorlariRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/yurist-bilan-boglanish': typeof YuristBilanBoglanishRoute
  '/yuristlar': typeof YuristlarRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/huquq-bolimlari/$slug': typeof HuquqBolimlariSlugRoute
  '/mamlakatlar/$countryId': typeof MamlakatlarCountryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/admin'
    | '/ai-tahlil'
    | '/case-database'
    | '/dashboard'
    | '/huquq-bolimlari'
    | '/jinoyat-kodeksi'
    | '/login'
    | '/mamlakatlar'
    | '/media'
    | '/notifications'
    | '/plenum-qarorlari'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/yurist-bilan-boglanish'
    | '/yuristlar'
    | '/api/ai-chat'
    | '/huquq-bolimlari/$slug'
    | '/mamlakatlar/$countryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/admin'
    | '/ai-tahlil'
    | '/case-database'
    | '/dashboard'
    | '/huquq-bolimlari'
    | '/jinoyat-kodeksi'
    | '/login'
    | '/mamlakatlar'
    | '/media'
    | '/notifications'
    | '/plenum-qarorlari'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/yurist-bilan-boglanish'
    | '/yuristlar'
    | '/api/ai-chat'
    | '/huquq-bolimlari/$slug'
    | '/mamlakatlar/$countryId'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/admin'
    | '/ai-tahlil'
    | '/case-database'
    | '/dashboard'
    | '/huquq-bolimlari'
    | '/jinoyat-kodeksi'
    | '/login'
    | '/mamlakatlar'
    | '/media'
    | '/notifications'
    | '/plenum-qarorlari'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/yurist-bilan-boglanish'
    | '/yuristlar'
    | '/api/ai-chat'
    | '/huquq-bolimlari/$slug'
    | '/mamlakatlar/$countryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRoute
  AiTahlilRoute: typeof AiTahlilRoute
  CaseDatabaseRoute: typeof CaseDatabaseRoute
  DashboardRoute: typeof DashboardRoute
  HuquqBolimlariRoute: typeof HuquqBolimlariRouteWithChildren
  JinoyatKodeksiRoute: typeof JinoyatKodeksiRoute
  LoginRoute: typeof LoginRoute
  MamlakatlarRoute: typeof MamlakatlarRouteWithChildren
  MediaRoute: typeof MediaRoute
  NotificationsRoute: typeof NotificationsRoute
  PlenumQarorlariRoute: typeof PlenumQarorlariRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  YuristBilanBoglanishRoute: typeof YuristBilanBoglanishRoute
  YuristlarRoute: typeof YuristlarRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yuristlar': {
      id: '/yuristlar'
      path: '/yuristlar'
      fullPath: '/yuristlar'
      preLoaderRoute: typeof YuristlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yurist-bilan-boglanish': {
      id: '/yurist-bilan-boglanish'
      path: '/yurist-bilan-boglanish'
      fullPath: '/yurist-bilan-boglanish'
      preLoaderRoute: typeof YuristBilanBoglanishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plenum-qarorlari': {
      id: '/plenum-qarorlari'
      path: '/plenum-qarorlari'
      fullPath: '/plenum-qarorlari'
      preLoaderRoute: typeof PlenumQarorlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mamlakatlar': {
      id: '/mamlakatlar'
      path: '/mamlakatlar'
      fullPath: '/mamlakatlar'
      preLoaderRoute: typeof MamlakatlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinoyat-kodeksi': {
      id: '/jinoyat-kodeksi'
      path: '/jinoyat-kodeksi'
      fullPath: '/jinoyat-kodeksi'
      preLoaderRoute: typeof JinoyatKodeksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huquq-bolimlari': {
      id: '/huquq-bolimlari'
      path: '/huquq-bolimlari'
      fullPath: '/huquq-bolimlari'
      preLoaderRoute: typeof HuquqBolimlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-database': {
      id: '/case-database'
      path: '/case-database'
      fullPath: '/case-database'
      preLoaderRoute: typeof CaseDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tahlil': {
      id: '/ai-tahlil'
      path: '/ai-tahlil'
      fullPath: '/ai-tahlil'
      preLoaderRoute: typeof AiTahlilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mamlakatlar/$countryId': {
      id: '/mamlakatlar/$countryId'
      path: '/$countryId'
      fullPath: '/mamlakatlar/$countryId'
      preLoaderRoute: typeof MamlakatlarCountryIdRouteImport
      parentRoute: typeof MamlakatlarRoute
    }
    '/huquq-bolimlari/$slug': {
      id: '/huquq-bolimlari/$slug'
      path: '/$slug'
      fullPath: '/huquq-bolimlari/$slug'
      preLoaderRoute: typeof HuquqBolimlariSlugRouteImport
      parentRoute: typeof HuquqBolimlariRoute
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HuquqBolimlariRouteChildren {
  HuquqBolimlariSlugRoute: typeof HuquqBolimlariSlugRoute
}

const HuquqBolimlariRouteChildren: HuquqBolimlariRouteChildren = {
  HuquqBolimlariSlugRoute: HuquqBolimlariSlugRoute,
}

const HuquqBolimlariRouteWithChildren = HuquqBolimlariRoute._addFileChildren(
  HuquqBolimlariRouteChildren,
)

interface MamlakatlarRouteChildren {
  MamlakatlarCountryIdRoute: typeof MamlakatlarCountryIdRoute
}

const MamlakatlarRouteChildren: MamlakatlarRouteChildren = {
  MamlakatlarCountryIdRoute: MamlakatlarCountryIdRoute,
}

const MamlakatlarRouteWithChildren = MamlakatlarRoute._addFileChildren(
  MamlakatlarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRoute,
  AiTahlilRoute: AiTahlilRoute,
  CaseDatabaseRoute: CaseDatabaseRoute,
  DashboardRoute: DashboardRoute,
  HuquqBolimlariRoute: HuquqBolimlariRouteWithChildren,
  JinoyatKodeksiRoute: JinoyatKodeksiRoute,
  LoginRoute: LoginRoute,
  MamlakatlarRoute: MamlakatlarRouteWithChildren,
  MediaRoute: MediaRoute,
  NotificationsRoute: NotificationsRoute,
  PlenumQarorlariRoute: PlenumQarorlariRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  YuristBilanBoglanishRoute: YuristBilanBoglanishRoute,
  YuristlarRoute: YuristlarRoute,
  ApiAiChatRoute: ApiAiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
